"""Fix: Give is_direct_message a default value of False

Revision ID: 075a44b10c3f
Revises: 7afd255cf047
Create Date: 2025-08-09 05:06:02.125145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075a44b10c3f'
down_revision: Union[str, Sequence[str], None] = '7afd255cf047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
