"""Add is_direct_message to ChatRoom table

Revision ID: 7afd255cf047
Revises: abfd6fc5601d
Create Date: 2025-08-08 07:21:16.253708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afd255cf047'
down_revision: Union[str, Sequence[str], None] = 'abfd6fc5601d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatrooms', sa.Column('is_direct_message', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatrooms', 'is_direct_message')
    # ### end Alembic commands ###
