"""add token_jti for blacklist

Revision ID: abfd6fc5601d
Revises: 92771b1c06da
Create Date: 2025-08-02 00:13:16.149423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abfd6fc5601d'
down_revision: Union[str, Sequence[str], None] = '92771b1c06da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklistedtokens', sa.Column('token_jti', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'blacklistedtokens', ['token_jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blacklistedtokens', type_='unique')
    op.drop_column('blacklistedtokens', 'token_jti')
    # ### end Alembic commands ###
